language: java
sudo: false
install: true

addons:
  sonarcloud:
    organization: "iodar-github"
    token:
      secure: "Mj5xEmf9RobIdCbAdN3K9ABJJ70LDrP4/BDwYueXPg+/DpBp61iI7E7R2zdtWvgejI3muvYXOziamqkbFzaGDsNBxqTGD0McuX4R/ilP41HhwhtH8AckB/HfEnMBaUPVZUOHkTEA/D6nVDoz7pldWVQtOCef4zC0T4mdbF2wFtBxloSQed6URKyH/muNy1Osh7X7Kn/Mst7h8uV1xA9H8Q3mT656ts6qgJj3cefHl3QEKRso97t6XN8bCXpTUAeFpFNOTg7MDAllq8FsEdW+Q0B2KteN74T3hNaZc4fwzXpKdlTGsidsAUoIbI1iYTKhNCZlkI5YL0gp8zqNezJr5+tfStyD58QdEE8Pr5+RLr1lr3as8gdmnQuyqV8kXoPnOMta7d+kOErDDNzDpE7R8lHBCX5sHVlYRD3V9N4UFSS8qfJkcf/X/BOl28MvxH4FolmsInjBJ9iWI+IgFNaiTbDHM4vptaitaVKhmU9hJXLgL/pqH5pqdu/zKN7fgYr0pR8rK4aDGEU6CYlFNdPx7pMjrykBGlUx4dLlTiEYY3wyjO6Ho4VIoeNotHxfBTA66viGmutZZjfoH27NBVIGtmg8n1OFNCmYwFxXn++zdF/bX7KXXPCdSf0qlAl5RNbVkIicMtOeO0to6u5KCsAxdW33T4Dwp7LXpBQEbqc9EFg="

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar